name: Actions Workflow 2

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS
        id: greetid
        uses: actions/hello-world-javascript-action@v1
        with:
          how-to-greet: Tim
      - name: log-greeting-time
        run: echo "${{ steps.greetid.outputs.time }}"
